apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: secureflow
  labels:
    app: auth-service
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: auth-service
  template:
    metadata:
      labels:
        svc: auth-service
        app: auth-service
        team: devsecops
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "auth-service-role"
        vault.hashicorp.com/agent-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-init-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-inject-template-auth-secrets: |
          {{- with secret "secureflow/data/auth-service" -}}
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          {{- end }}
    spec:
      serviceAccountName: auth-service-sa
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: auth-service
          image: localhost:5001/secureflow/auth-service@sha256:a07f1ced66929d854e78b8d118f4449008145820058a4b9b66da49cf3dba39ee
          command: ["/bin/sh", "-c"]
          args:
            - . /vault/secrets/auth-secrets && exec python app.py
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: secureflow-config
          env:
            - name: DB_HOST
              value: auth-db
            - name: DB_NAME
              value: authdb
            - name: DB_USER
              value: authuser
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: secureflow
  labels:
    app: auth-service
    team: devsecops
spec:
  selector:
    svc: auth-service
  ports:
    - port: 5001
      targetPort: 5001
