apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: secureflow
  labels:
    app: auth-db
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: auth-db
  template:
    metadata:
      labels:
        svc: auth-db
        app: auth-db
        team: devsecops
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              value: authuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secureflow-config
                  key: AUTH_DB_PASSWORD
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: secureflow
  labels:
    app: auth-db
    team: devsecops
spec:
  selector:
    svc: auth-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-db
  namespace: secureflow
  labels:
    app: transaction-db
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-db
  template:
    metadata:
      labels:
        svc: transaction-db
        app: transaction-db
        team: devsecops
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: transactiondb
            - name: POSTGRES_USER
              value: txuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secureflow-config
                  key: TX_DB_PASSWORD
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-db
  namespace: secureflow
  labels:
    app: transaction-db
    team: devsecops
spec:
  selector:
    svc: transaction-db
  ports:
    - port: 5432
      targetPort: 5432
