apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: secureflow
  labels:
    app: auth-db
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: auth-db
  template:
    metadata:
      labels:
        svc: auth-db
        app: auth-db
        team: devsecops
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "auth-db-role"
        vault.hashicorp.com/agent-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":100,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-init-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":100,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-inject-template-auth-db-secrets: |
          {{- with secret "secureflow/data/auth-service" -}}
          export POSTGRES_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          {{- end }}
    spec:
      serviceAccountName: auth-db-sa
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data /var/run/postgresql"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: pg-run
              mountPath: /var/run/postgresql
      containers:
        - name: postgres
          image: postgres:14
          command: ["/bin/sh", "-c"]
          args:
            - . /vault/secrets/auth-db-secrets && exec docker-entrypoint.sh postgres
          env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              value: authuser
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: pg-run
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: pg-data
          emptyDir: {}
        - name: pg-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: secureflow
  labels:
    app: auth-db
    team: devsecops
spec:
  selector:
    svc: auth-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-db
  namespace: secureflow
  labels:
    app: transaction-db
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-db
  template:
    metadata:
      labels:
        svc: transaction-db
        app: transaction-db
        team: devsecops
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-db-role"
        vault.hashicorp.com/agent-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":100,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-init-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":100,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-inject-template-tx-db-secrets: |
          {{- with secret "secureflow/data/transaction-service" -}}
          export POSTGRES_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          {{- end }}
    spec:
      serviceAccountName: transaction-db-sa
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data /var/run/postgresql"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: pg-run
              mountPath: /var/run/postgresql
      containers:
        - name: postgres
          image: postgres:14
          command: ["/bin/sh", "-c"]
          args:
            - . /vault/secrets/tx-db-secrets && exec docker-entrypoint.sh postgres
          env:
            - name: POSTGRES_DB
              value: transactiondb
            - name: POSTGRES_USER
              value: txuser
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - FOWNER
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: pg-run
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: pg-data
          emptyDir: {}
        - name: pg-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-db
  namespace: secureflow
  labels:
    app: transaction-db
    team: devsecops
spec:
  selector:
    svc: transaction-db
  ports:
    - port: 5432
      targetPort: 5432
