apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: secureflow
  labels:
    app: transaction-service
    team: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-service
  template:
    metadata:
      labels:
        svc: transaction-service
        app: transaction-service
        team: devsecops
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transaction-service-role"
        vault.hashicorp.com/agent-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":100,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-init-json-patch: '[{"op":"add","path":"/securityContext","value":{"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":100,"capabilities":{"drop":["ALL"]}}}]'
        vault.hashicorp.com/agent-inject-template-tx-secrets: |
          {{- with secret "secureflow/data/transaction-service" -}}
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          {{- end }}
    spec:
      volumes:
        - name: tmp
          emptyDir: {}
      serviceAccountName: transaction-service-sa
      containers:
        - name: transaction-service
          image: localhost:5001/secureflow/transaction-service@sha256:61b9aefdb82238677d884d3d0d2253efcca42135bdc660f28269a1d950ab040f
          command: ["/bin/sh", "-c"]
          args:
            - . /vault/secrets/tx-secrets && exec python app.py
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: secureflow-config
          env:
            - name: DB_HOST
              value: transaction-db
            - name: DB_NAME
              value: transactiondb
            - name: DB_USER
              value: txuser
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 100
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: secureflow
  labels:
    app: transaction-service
    team: devsecops
spec:
  selector:
    svc: transaction-service
  ports:
    - port: 5002
      targetPort: 5002
