apiVersion: v1
kind: Service
metadata:
  name: falco-metrics
  namespace: falco
  labels:
    app: falco-metrics
spec:
  selector:
    app.kubernetes.io/name: falco
    app.kubernetes.io/instance: falco
  ports:
    - name: metrics
      port: 8765
      targetPort: 8765
